name: ai_scribe_copilot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  path_provider: ^2.1.5
  http: ^1.5.0

  # Audio Recording - Primary Package
  flutter_sound: ^9.28.0  # Most comprehensive audio solution
  just_audio: ^0.9.40
  audio_video_progress_bar: ^2.0.3
  # Background Processing & Lifecycle Management
  flutter_background_service: ^5.0.10  # Background recording capability
  flutter_background_service_android: ^6.2.5
  workmanager: ^0.5.2  # Periodic background tasks
  flutter_foreground_task: ^8.17.0
  audio_session: ^0.1.25
  # App Lifecycle & State Management
  # app_lifecycle: ^0.0.4  # Better lifecycle detection
  # flutter_app_lifecycle: ^1.0.1  # Enhanced app state tracking
  
  # Network & Connectivity Management
  connectivity_plus: ^6.0.3  # Network state monitoring
  internet_connection_checker: ^3.0.0  # Reliable internet checking
  intl: ^0.20.2
  # Permissions
  permission_handler: ^12.0.1  # All permissions management
  
  # Phone Call Detection
  # phone_state: ^2.0.0  # Phone call state detection
  

  # Storage & Queue Management  
  sqflite: ^2.3.3  # Local database for queuing
  shared_preferences: ^2.2.2  # Simple state persistence
  
  # File & Upload Management
  dio: ^5.4.3+1  # Advanced HTTP client with retry logic
  file_picker: ^8.0.6  # File operations
  
  # Notifications (for background status)
  flutter_local_notifications: ^17.2.2
  
  # Device Info & System Integration
  device_info_plus: ^10.1.2  # Device capabilities detection
  battery_plus: ^6.0.2  # Battery optimization awareness
  
  # Audio Processing & Analysis
  wav: ^1.0.0  # WAV file manipulation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter  # For your test cases

flutter:
  uses-material-design: true